integrate detekt and ktlint configs

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,14 +1,14 @@
 #!/bin/bash
 
-echo "Running git pre-commit hook"
+cd "$(dirname "$0")/pre-commit.d"
 
-./gradlew ktlintCheck
+for hook in *; do
+    bash $hook
+    RESULT=$?
+    if [ $RESULT != 0 ]; then
+        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
+        exit $RESULT
+    fi
+done
 
-ktlintCheckStatus=$?
-
-# return 1 if check fails
-if [[ $ktlintCheckStatus -ne 0 ]]; then
-     exit 1
-else
-     exit 0
-fi
+exit 0
